# database configurations for all environments(production, test, development) will be done here.

development:
  adapter: postgresql
  database: sinatra_dev
  username: ENV['POSTGRES_USERNAME']
  password: ENV['POSTGRES_PASSWORD']
  host: localhost